CREATE DATABASE IF NOT EXISTS CLINICA_MEDICA_SAEP_DB;
USE CLINICA_MEDICA_SAEP_DB;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_ID INT AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(100) NOT NULL,
    USU_EMAIL VARCHAR(100) NOT NULL,
    USU_SENHA VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS RESPONSAVEL(
	RES_ID INT AUTO_INCREMENT PRIMARY KEY, 
    RES_NOME VARCHAR(100) NOT NULL,
    RES_DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS PACIENTE(
	PAC_ID INT AUTO_INCREMENT PRIMARY KEY,
    PAC_NOME VARCHAR(100) NOT NULL,
    PAC_DATA_NASCIMENTO DATE NOT NULL,
    FK_RES_ID INT NOT NULL,
    FOREIGN KEY (FK_RES_ID) REFERENCES RESPONSAVEL(RES_ID)
);

CREATE TABLE IF NOT EXISTS AGENDAMENTO(
	AGE_ID INT AUTO_INCREMENT PRIMARY KEY,
    AGE_DATA_HORA DATETIME NOT NULL,
    AGE_MOTIVO VARCHAR(100) NOT NULL,
    AGE_STATUS VARCHAR(30) NOT NULL,
    FK_PAC_ID INT NOT NULL,
    FK_RES_ID INT NOT NULL,
    FOREIGN KEY (FK_PAC_ID) REFERENCES PACIENTE(PAC_ID),
    FOREIGN KEY (FK_RES_ID) REFERENCES RESPONSAVEL(RES_ID)
);

INSERT INTO USUARIO(USU_NOME, USU_EMAIL, USU_SENHA)
VALUES 	("Admin", "admin@admin.com", "admin123"),
		("Gabriel", "gabriel@email.com", "123456"),
        ("Luiz", "luiz@email.com", "123456");
        
INSERT INTO RESPONSAVEL(RES_NOME, RES_DATA_NASCIMENTO)
VALUES 	("Gabriel", "2000-07-16"), 	-- RES_ID - 1
		("Luiz", "1800-01-01"), 	-- RES_ID - 2
        ("Leonardo", "1998-10-10"); -- RES_ID - 3
        
INSERT INTO PACIENTE(PAC_NOME, PAC_DATA_NASCIMENTO, FK_RES_ID)
VALUES 	("Livia", "2024-04-05", 2), 	-- PAC_ID - 1
		("Pantufa", "2024-05-17", 1),	-- PAC_ID - 2
		("Lola", "2020-10-01", 3);		-- PAC_ID - 3
        
INSERT INTO AGENDAMENTO(AGE_DATA_HORA, AGE_MOTIVO, AGE_STATUS, FK_PAC_ID, FK_RES_ID)
VALUES 	("2026-09-29 08:00:00", "Gripe", "Agendada", 1, 2),
		("2026-09-29 08:30:00", "Dor de barriga", "Agendada", 2, 1),
		("2026-09-29 09:00:00", "Comeu rato", "Agendada", 3, 3);




